# Generated by Django 3.0.4 on 2020-03-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0002_auto_20200326_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='due_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
